### ISSUE TITLE
Vue example

### ISSUE THREAD

**Issue by colem213** [ipfs-examples/js-ipfs-examples#35]
I'm getting these errors when trying to run the browser-vue example:

```
 ERROR  Failed to compile with 2 errors                                                                                              3:08:46 AM

 error  in ./node_modules/levelup/lib/levelup.js

Module not found: Error: Can't resolve 'util' in '/workspaces/js-ipfs-examples/examples/browser-vue/node_modules/levelup/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

 error  in ./node_modules/libp2p-kad-dht/src/routing-table/index.js

Module not found: Error: Can't resolve './generated-prefix-list.json' in '/workspaces/js-ipfs-examples/examples/browser-vue/node_modules/libp2p-kad-dht/src/routing-table'
```

**Comment by pfnsec** [comment]
I'm also running into this... Any resolution?

**Comment by oliveriosousa** [comment]
Hi @colem213 and @pfnsec 

Yes, this has been fixed https://github.com/libp2p/js-libp2p-kad-dht/commit/3c737c16399ac7e541b417f0e8b76157ed2f86ff 

Sorry for the late response.

**Comment by achingbrain** [comment]
This would have been resolved by https://github.com/ipfs-examples/js-ipfs-examples/pull/39/files#diff-b6fd22426b3d8c26af1a29d8e2f5646d94d2a755efcf03ef8b931a8dc3f70bafR52

**Comment by oliveriosousa** [comment]
The error showed is fixed but still fails to build. 

See https://github.com/ipfs-examples/js-ipfs-examples/pull/42

**Comment by achingbrain** [comment]
This should be fixed by https://github.com/webpack/enhanced-resolve/issues/304

**Comment by oliveriosousa** [comment]
This issue has been fixed https://github.com/webpack/enhanced-resolve/issues/304

Please, run `yarn clean` in the root of the project and do a clean install `yarn install`

Sorry for the late response, let me know if you still get some erros
